// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quuayvprtbwwvfkufyqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dWF5dnBydGJ3d3Zma3VmeXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzAwMjcsImV4cCI6MjA3MjMwNjAyN30.aNi0NL3HVFjuLWcnM-c-F2IyLFaZdkRIO2Cg6Sw4OjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});